#!/usr/bin/env bash

OPTIONS_STUCKLONG=t
# shellcheck disable=SC2034
OPTIONS_KEEPDASHDASH=
# shellcheck disable=SC2034
OPTIONS_SPEC="\
switch [options]
switch [env] [network]
--
  Switch pre/default dns config.
  http://10.172.94.171/frontend/xian/switch

  Available options are
p,pre!      switch pre dns
"

# Defaults
is_pre=0
is_default=0

while test $# != 0; do
  case "$1" in
  --pre) is_pre=1;;
  --) shift; break ;;
  esac
  shift
done

if (( is_pre )); then
  networksetup -setdnsservers Wi-Fi 182.92.129.95
  echo "now is pre env!"
  # networksetup -setdnsservers Thunderbolt 182.92.129.95
else
  networksetup -setdnsservers Wi-Fi empty
  echo "now is default env!"
  # networksetup -setdnsservers Thunderbolt empty
fi
